(()=>{if(!window.gsap||innerWidth<1201)return;window.CustomEase&&gsap.registerPlugin&&(gsap.registerPlugin(CustomEase),CustomEase.create("lm-anim","0.26, 0.82, 0.38, 1"));const e=window.CustomEase?"lm-anim":"power2.out",t=document.querySelector(".lm-float"),o=t&&t.querySelector(".lm-wrap");if(!t||!o)return;const i=t.querySelector(".lm-text");let s=!1,r=null;const a=gsap.quickSetter(t,"x","px"),l=gsap.quickSetter(t,"y","px");gsap.set(t,{opacity:1}),gsap.set(t,{height:0,backgroundColor:"transparent",scale:0,padding:0,overflow:"hidden",xPercent:-50,yPercent:-50}),gsap.set(o,{width:0,overflow:"hidden"}),gsap.set(".lm-st",{opacity:0});const n=e=>{s&&(a(e.clientX),l(e.clientY))};window.addEventListener("mousemove",n,{passive:!0});const c=()=>{const e=o.style.width,i=t.style.height;o.style.width="auto",t.style.height="auto";const s=o.offsetWidth,r=t.offsetHeight;return o.style.width=e,t.style.height=i,{ww:s,hh:r}},d=()=>{r&&r.kill(),r=null,gsap.killTweensOf([t,o,".lm-st"])},u=e=>{s=!0,gsap.set(t,{opacity:1}),i&&(i.textContent=e.currentTarget?.dataset?.lm||""),n(e),d();const{ww:a,hh:l}=c();r=gsap.timeline({defaults:{overwrite:"auto"}}).to(t,{height:l,backgroundColor:"#cacaca",scale:1,padding:1,duration:.5,ease:e},0).to(o,{width:a,duration:.45,ease:e},0).to(".lm-st",{opacity:1,duration:.3,ease:"none"},0).set(t,{height:"auto"}).set(o,{width:"auto"})},p=()=>{d();const i=o.offsetWidth,a=t.offsetHeight;r=gsap.timeline({defaults:{overwrite:"auto"},onComplete:()=>{s=!1,gsap.set(t,{opacity:0})}}).set(t,{height:a}).set(o,{width:i}).set(".lm-st",{opacity:0}).to(o,{width:0,duration:.4,ease:e},0).to(t,{height:0,backgroundColor:"transparent",padding:0,scale:0,duration:.4,ease:e},0)};document.querySelectorAll(".lm-hover").forEach(e=>{e.addEventListener("mouseenter",u),e.addEventListener("mouseleave",p)})})();

// lm-float — cursor-follow hover preview.
// On hover: reads text from data-lm, moves container with cursor, expands wrapper,
// fades in content; on leave: collapses back. Uses quickSetter + timeline for smoothness.
// Disabled on small screens (<1201px), supports CustomEase if present.

// Markup hooks:
// .lm-hover (hover trigger), data-lm (text source),
// .lm-float (floating container), .lm-wrap (inner size wrapper), .lm-st (animated content).